version: '3'

services:
  container:
    build: .
    image: dev_img
    volumes:
      - ~/git_repo:/opt/git_repo
      - ./program_files:/opt/program_files
      - ./setup_files:/opt/setup_files
      - ./home_dir:/root/home_dir/
      - ./install.sh:/opt/install.sh
    stdin_open: true
    tty: true
    # container_name: dev
    ports:
      - "18888:8888"

networks:
  default:
    external: 
      name: hf_dev_network
